meta_title: "Créapolis"
meta_description: "Creapolis est une web application de géolocalisation d'oeuvres d'arts urbains"
# Une image dans votre dossier app/assets/images/
meta_image: "meta_image.jpg"                        